# Generated by Django 4.1.2 on 2022-10-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('lattes', models.URLField()),
                ('google_scholar', models.URLField()),
                ('research_gate', models.URLField()),
                ('linkedin', models.URLField()),
                ('orcid', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('lattes', models.URLField()),
                ('google_scholar', models.URLField()),
                ('research_gate', models.URLField()),
                ('linkedin', models.URLField()),
                ('orcid', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CoAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('lattes', models.URLField()),
                ('google_scholar', models.URLField()),
                ('research_gate', models.URLField()),
                ('linkedin', models.URLField()),
                ('orcid', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Monography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('summary', models.CharField(max_length=100)),
                ('key_words', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=80)),
                ('course', models.CharField(max_length=50)),
                ('monography', models.URLField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monografias.advisor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monografias.author')),
                ('co_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monografias.coadvisor')),
            ],
        ),
    ]
