# Generated by Django 4.1.3 on 2022-11-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monografias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monography',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monografias.author'),
        ),
        migrations.AlterField(
            model_name='monography',
            name='summary',
            field=models.TextField(),
        ),
    ]
